### ISSUE TITLE
if you using filter then no need to clone the array

### ISSUE THREAD

**Issue by Walidmash** [FACG4/Week2-IRMS-To-Do#31]
https://github.com/FACG4/Week2-IRMS-To-Do/blob/8ccb1586bc95ff8ca82d7eba2a842589ed0fff08/logic.js#L37

Filter returns new copy of the array, thats why you don't need to make an extra copy of your data by using ```cloneArrayOfObjects```
and you should get use on using ```!==``` instead of ```!=```

**Comment by sallamTanna** [comment]
We edited it, thank you :)
